use serde::Deserialize;

use crate::model::{NumberString, OrderSide, PositionSide, TradeMode};

/// Result of moving positions between master and sub-accounts.
#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
#[non_exhaustive]
pub struct MovePositionsResult {
    /// Client-supplied transfer ID.
    #[serde(default)]
    pub client_id: String,
    /// Block trade ID generated by OKX.
    #[serde(default)]
    pub block_td_id: String,
    /// Transfer state.
    #[serde(default)]
    pub state: String,
    /// Processing timestamp in Unix milliseconds.
    #[serde(default)]
    pub ts: NumberString,
    /// Source account name. `0` identifies the master account.
    #[serde(default)]
    pub from_acct: String,
    /// Destination account name. `0` identifies the master account.
    #[serde(default)]
    pub to_acct: String,
    /// Per-position transfer results.
    #[serde(default)]
    pub legs: Vec<MovePositionLegResult>,
}

/// Result for one position-transfer leg.
#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
#[non_exhaustive]
pub struct MovePositionLegResult {
    /// Source-side result.
    pub from: MovePositionFromResult,
    /// Destination-side result.
    pub to: MovePositionToResult,
}

/// Source-side result for one position-transfer leg.
#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
#[non_exhaustive]
pub struct MovePositionFromResult {
    /// Source position ID.
    #[serde(default)]
    pub pos_id: String,
    /// Instrument ID.
    #[serde(default)]
    pub inst_id: String,
    /// Transfer price.
    #[serde(default)]
    pub px: NumberString,
    /// Source-side trade direction.
    pub side: OrderSide,
    /// Number of contracts.
    #[serde(default)]
    pub sz: NumberString,
    /// Per-leg OKX result code. Present on transfer responses.
    #[serde(default)]
    pub s_code: String,
    /// Per-leg OKX result message. Present on transfer responses.
    #[serde(default)]
    pub s_msg: String,
}

/// Destination-side result for one position-transfer leg.
#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
#[non_exhaustive]
pub struct MovePositionToResult {
    /// Instrument ID.
    #[serde(default)]
    pub inst_id: String,
    /// Transfer price.
    #[serde(default)]
    pub px: NumberString,
    /// Destination-side trade direction.
    pub side: OrderSide,
    /// Number of contracts.
    #[serde(default)]
    pub sz: NumberString,
    /// Destination trading mode.
    pub td_mode: TradeMode,
    /// Destination position side.
    pub pos_side: PositionSide,
    /// Destination margin currency.
    #[serde(default)]
    pub ccy: String,
    /// Per-leg OKX result code. Present on transfer responses.
    #[serde(default)]
    pub s_code: String,
    /// Per-leg OKX result message. Present on transfer responses.
    #[serde(default)]
    pub s_msg: String,
}

/// Position-builder trend graph result.
#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
#[non_exhaustive]
pub struct PositionBuilderGraphResult {
    /// Graph type.
    #[serde(rename = "type", default)]
    pub graph_type: String,
    /// Maintenance-margin data, ordered by shock factor.
    #[serde(default)]
    pub mmr_data: Vec<PositionBuilderGraphPoint>,
}

/// One point in a position-builder MMR trend graph.
#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
#[non_exhaustive]
pub struct PositionBuilderGraphPoint {
    /// Price change ratio in the range -1 to 1.
    #[serde(default)]
    pub shock_factor: NumberString,
    /// Maintenance margin at this price shock.
    #[serde(default)]
    pub mmr: NumberString,
    /// Maintenance margin ratio at this price shock.
    #[serde(default)]
    pub mmr_ratio: NumberString,
}
