pub(super) const TICKER: &str = "/api/v5/market/ticker";
pub(super) const TICKERS: &str = "/api/v5/market/tickers";
pub(super) const INDEX_TICKERS: &str = "/api/v5/market/index-tickers";
pub(super) const BOOKS: &str = "/api/v5/market/books";
pub(super) const BOOKS_LITE: &str = "/api/v5/market/books-lite";
pub(super) const CANDLES: &str = "/api/v5/market/candles";
pub(super) const HISTORY_CANDLES: &str = "/api/v5/market/history-candles";
pub(super) const INDEX_CANDLES: &str = "/api/v5/market/index-candles";
pub(super) const MARK_PRICE_CANDLES: &str = "/api/v5/market/mark-price-candles";
pub(super) const TRADES: &str = "/api/v5/market/trades";
pub(super) const HISTORY_TRADES: &str = "/api/v5/market/history-trades";
pub(super) const PLATFORM_24_VOLUME: &str = "/api/v5/market/platform-24-volume";
pub(super) const INDEX_COMPONENTS: &str = "/api/v5/market/index-components";
pub(super) const EXCHANGE_RATE: &str = "/api/v5/market/exchange-rate";
pub(super) const BLOCK_TICKER: &str = "/api/v5/market/block-ticker";
pub(super) const BLOCK_TICKERS: &str = "/api/v5/market/block-tickers";
pub(super) const BLOCK_TRADES: &str = "/api/v5/market/block-trades";
pub(super) const OPTION_INSTRUMENT_FAMILY_TRADES: &str =
    "/api/v5/market/option/instrument-family-trades";
